name: yantene.net
description: やんてねの雑記帳
author: yantene
url: https://yantene.net
encoding: utf-8
permalink: :title.html

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  syntax_highlighter: rouge

exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'deploy.sh']
